<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="lib.listeners.RetryListener"/>
  </listeners>
  <test thread-count="5" name="Incident(failed)">
    <classes>
      <class name="tests.rest.TC004_UpdateIncident">
        <methods>
          <include name="beforeClass"/>
          <include name="setValues"/>
          <include name="beforeMethod"/>
          <include name="beforeSuite"/>
          <include name="UpdateIncident" invocation-numbers="0"/>
          <include name="afterSuite"/>
        </methods>
      </class> <!-- tests.rest.TC004_UpdateIncident -->
      <class name="tests.rest.TC001_CreateIncident">
        <methods>
          <include name="setValues"/>
          <include name="beforeClass"/>
          <include name="createIncident"/>
          <include name="beforeMethod"/>
          <include name="beforeSuite"/>
          <include name="afterSuite"/>
        </methods>
      </class> <!-- tests.rest.TC001_CreateIncident -->
    </classes>
  </test> <!-- Incident(failed) -->
</suite> <!-- Failed suite [Suite] -->
